/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "GoalsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "KindeClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KindeClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "KindeDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "MasterApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "MasterBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "MasterWeb": {
      "type": "sst.aws.React"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}